export const Trading = {
    PercentOrFixed: [
        { label: 'Percent', value: 'Percent' },
        { label: 'Fixed Price', value: 'Fixed Price' },     
    ],
    Result: [
        { label: 'Win', value: 'Win' },
        { label: 'Loss', value: 'Loss' },
    ],
    Sessions: [
        { label: 'London Session', value: 'London Session' },
        { label: 'London / New York Overlap', value: 'London / New York Overlap' },
        { label: 'New York Session', value: 'New York Session' },
        { label: 'Sydney Session', value: 'Sydney Session' },
        { label: 'Sydney / Tokyo Overlap', value: 'Sydney / Tokyo Overlap' },
        { label: 'Tokyo Session', value: 'Tokyo Session' },
        { label: 'Tokyo / London Overlap', value: 'Tokyo / London Overlap' },
    ],
    Assets: [
        { label: 'EUR/USD', value: 'EUR/USD' },
        { label: 'GBP/USD', value: 'GBP/USD' },
        { label: 'USD/JPY', value: 'USD/JPY' },
        { label: 'AUD/USD', value: 'AUD/USD' },
        { label: 'USD/CAD', value: 'USD/CAD' },
        { label: 'NZD/USD', value: 'NZD/USD' },
        { label: 'USD/CHF', value: 'USD/CHF' },
        { label: 'EUR/GBP', value: 'EUR/GBP' },
        { label: 'EUR/JPY', value: 'EUR/JPY' },
        { label: 'EUR/AUD', value: 'EUR/AUD' },
        { label: 'EUR/NZD', value: 'EUR/NZD' },
        { label: 'EUR/CHF', value: 'EUR/CHF' },
        { label: 'EUR/CAD', value: 'EUR/CAD' },
        { label: 'GBP/JPY', value: 'GBP/JPY' },
        { label: 'GBP/AUD', value: 'GBP/AUD' },
        { label: 'GBP/NZD', value: 'GBP/NZD' },
        { label: 'GBP/CAD', value: 'GBP/CAD' },
        { label: 'GBP/CHF', value: 'GBP/CHF' },
        { label: 'AUD/JPY', value: 'AUD/JPY' },
        { label: 'AUD/NZD', value: 'AUD/NZD' },
        { label: 'AUD/CAD', value: 'AUD/CAD' },
        { label: 'AUD/CHF', value: 'AUD/CHF' },
        { label: 'NZD/JPY', value: 'NZD/JPY' },
        { label: 'NZD/CHF', value: 'NZD/CHF' },
        { label: 'NZD/CAD', value: 'NZD/CAD' },
        { label: 'CAD/JPY', value: 'CAD/JPY' },
        { label: 'CAD/CHF', value: 'CAD/CHF' },
        { label: 'CHF/JPY', value: 'CHF/JPY' },
        { label: 'XAU/USD', value: 'XAU/USD' },
        { label: 'XAG/USD', value: 'XAG/USD' },
        { label: 'US30', value: 'US30' },
        { label: 'SPX500', value: 'SPX500' },
        { label: 'NAS100', value: 'NAS100' },
        { label: 'UK100', value: 'UK100' },
        { label: 'GER30', value: 'GER30' },
        { label: 'FRA40', value: 'FRA40' },
        { label: 'JP225', value: 'JP225' },
        { label: 'AUS200', value: 'AUS200' },
        { label: 'HK50', value: 'HK50' },
        { label: 'EU50', value: 'EU50' },
        { label: 'Other', value: 'Other' },
    ],
};